name: Android App Distribution

on:
  push:
    branches:
      - main

jobs:
  build-and-distribute:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      # Set up Flutter environment
      - uses: subosito/flutter-action@v1
        with:
            flutter-version: '3.19.0'

      # Setup Java JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set up Firebase Service Account
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}" | base64 --decode > $HOME/service-account-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/service-account-key.json" >> $GITHUB_ENV

      # Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Fetch dependencies and build the app
      - name: Fetch dependencies and build AK
        run: |
          flutter pub get
          flutter build apk --release

      # Distribute to Firebase App Distribution
      - name: Distribute APK to Firebase
        run: firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk --app ${{secrets.FIREBASE_APP_ID}} --token ${{secrets.FIREBASE_TOKEN}} --groups testers
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}