name: Android App Distribution

on:
  push:
    branches:
      - main

jobs:
  build-and-distribute:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      # Setup Java JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      # Build APK
      - name: Build Release APK
        run: flutter build apk --release
#        env:
#          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
#          ALIAS_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}

      # Distribute to Firebase App Distribution
      - name: Distribute APK to Firebase
        run: |
          firebase appdistribution:distribute ./build/app/outputs/flutter-apk/app-release.apk \
            --app 1:338371944427:android:d2b1ab96b0214f7dfb03ae \
            --token ${{ secrets.FIREBASE_TOKEN }} \
            --groups "beta-testers"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}