name: Deploy to Firebase App Distribution

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12' # Or the version you need
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.3' # Use the Flutter version your project requires
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk # or flutter build ios for iOS apps

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: 1:338371944427:android:d2b1ab96b0214f7dfb03ae # Find this in your Firebase project settings
          token: ${AAAATsiKH-s:APA91bFY8MPHFnL0rMeiZuGFtkntXJrXfRStr7x70mybjfpOlbdkt-5uxEN_1euWHc8mVPlmE4ru9qqrm7U1RYjEhrSCArUqWOFWWk9WxU5qsyQ6v5tqi0QZkg4vfQsgbKITuWrZYhtW}
          groups: testers # Or any other group you've set up in Firebase App Distribution
          file: build/app/outputs/flutter-apk/app-release.apk # Adjust path for your app's build output